config/routes.rb
Rails.application.routes.draw do
  
  match "/application.manifest" => Rails::Offline, via: [:get]

=begin
  offline = Rack::Offline.configure :cache_interval => 1 do
    cache ActionController::Base.helpers.asset_path("application.js")
    cache ActionController::Base.helpers.asset_path("jquery.tmpl.min.js")
    cache ActionController::Base.helpers.asset_path("jquery.offline.js")
    cache ActionController::Base.helpers.asset_path("json.js")
    cache ActionController::Base.helpers.asset_path("custom.js")
    cache ActionController::Base.helpers.asset_path("validate.js")
    cache ActionController::Base.helpers.asset_path("application.css")
    cache ActionController::Base.helpers.asset_path("style.css")
    cache ActionController::Base.helpers.asset_path("custom.css")
    
    public_path = Rails.public_path
    Dir[public_path.join("stylesheets/*.css")].each do |file|
      cache file.relative_path_from(public_path)
    end
    
    cache "/images/sb1.jpg"
    cache "/stylesheets/buildings.css"
    cache "/javascripts/buildings.js"
    
    network "/"
  end
  get "/application.manifest" => offline
=end
  
  get 'navigator/index'
  
  resources :layouts

  resources :floors

  resources :buildings

end

app/models/building.rb
class Building < ActiveRecord::Base
  has_many :floor, dependent: :destroy
  
  validates :name, :address, :postal_code, :image_url, presence: true
  validates :name, :address, :postal_code, uniqueness: true
  validates :image_url, allow_blank: true, format: {
    with: %r{\.(gif|jpg|png)\z}i,
    message: 'must be a URL for GIF, JPG, or PNG image.'
  }
end

app/controllers/buildings_controller.rb
class BuildingsController < ApplicationController
  before_action :set_building, only: [:show, :edit, :update, :destroy]

  # GET /buildings
  # GET /buildings.json
  def index
    @buildings = Building.all
    #render :json => @buildings
  end

  # GET /buildings/1
  # GET /buildings/1.json
  def show
  end

  # GET /buildings/new
  def new
    @building = Building.new
  end

  # GET /buildings/1/edit
  def edit
  end

  # POST /buildings
  # POST /buildings.json
  def create
    @building = Building.new(building_params)

    respond_to do |format|
      if @building.save
        format.html { redirect_to @building, notice: 'Building was successfully created.' }
        format.json { render :show, status: :created, location: @building }
      else
        format.html { render :new }
        format.json { render json: @building.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /buildings/1
  # PATCH/PUT /buildings/1.json
  def update
    respond_to do |format|
      if @building.update(building_params)
        format.html { redirect_to @building, notice: 'Building was successfully updated.' }
        format.json { render :show, status: :ok, location: @building }
      else
        format.html { render :edit }
        format.json { render json: @building.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /buildings/1
  # DELETE /buildings/1.json
  def destroy
    @building.destroy
    respond_to do |format|
      format.html { redirect_to buildings_url, notice: 'Building was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_building
      @building = Building.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def building_params
      params.require(:building).permit(:address, :name, :postal_code, :image_url)
    end
end

app/helpers/buildings_helper.rb
module BuildingsHelper
end

app/views/buildings/_form.html.erb
<%= form_for(@building) do |f| %>
  <% if @building.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@building.errors.count, "error") %> prohibited this building from being saved:</h2>

      <ul>
      <% @building.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_area :address, rows:6 %>
  </div>
  
  <div class="field">
    <%= f.label :postal_code %><br>
    <%= f.text_field :postal_code %>
  </div>
  
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
  
<% end %>

app/views/buildings/edit.html.erb
<h1>Editing building</h1>

<%= render 'form' %>

<%= link_to 'Show', @building %> |
<%= link_to 'Back', buildings_path %>

app/views/buildings/index.html.erb
<h1>Listing buildings</h1>

<table>
  <tbody>
    <% @buildings.each do |building| %>
      <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
     	<td>
       		<%= image_tag(building.image_url, class: 'list_image') %>
        </td>
      	<td class="list_description">
      		<dl>
      			<dt><%= building.name %></dt>
      			<dd><%= truncate(strip_tags(building.address), length: 80) %></dd>
      			<dd><%= building.postal_code %></dd>
      		</dl>
      	</td>
        <td class="list_actions">
        	<%= link_to 'Floors', floors_path(:building_id => building.id) %><br/>
        	<%= link_to 'Show', building %><br/>
        	<%= link_to 'Edit', edit_building_path(building) %><br/>
        	<%= link_to 'Destroy', building, method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Building', new_building_path %>

app/views/buildings/new.html.erb
<h1>New building</h1>

<%= render 'form' %>

<%= link_to 'Back', buildings_path %>

app/views/buildings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Address:</strong>
  <%= @building.address %>
</p>

<p>
  <strong>Name:</strong>
  <%= @building.name %>
</p>

<p>
  <strong>Postal code:</strong>
  <%= @building.postal_code %>
</p>

<%= link_to 'Edit', edit_building_path(@building) %> |
<%= link_to 'Back', buildings_path %>