config/routes.rb
Rails.application.routes.draw do
  
  match "/application.manifest" => Rails::Offline, via: [:get]

=begin
  offline = Rack::Offline.configure :cache_interval => 1 do
    cache ActionController::Base.helpers.asset_path("application.js")
    cache ActionController::Base.helpers.asset_path("jquery.tmpl.min.js")
    cache ActionController::Base.helpers.asset_path("jquery.offline.js")
    cache ActionController::Base.helpers.asset_path("json.js")
    cache ActionController::Base.helpers.asset_path("custom.js")
    cache ActionController::Base.helpers.asset_path("validate.js")
    cache ActionController::Base.helpers.asset_path("application.css")
    cache ActionController::Base.helpers.asset_path("style.css")
    cache ActionController::Base.helpers.asset_path("custom.css")
    
    public_path = Rails.public_path
    Dir[public_path.join("stylesheets/*.css")].each do |file|
      cache file.relative_path_from(public_path)
    end
    
    cache "/images/sb1.jpg"
    cache "/stylesheets/buildings.css"
    cache "/javascripts/buildings.js"
    
    network "/"
  end
  get "/application.manifest" => offline
=end
  
  get 'navigator/index'
  
  resources :layouts

  resources :floors

  resources :buildings

end

app/models/floor.rb
class Floor < ActiveRecord::Base
  belongs_to :building
  has_many :layout, dependent: :destroy
  
  validates :number, :code, :building, presence: true
  validates :number, numericality: {greater_than: 0}
end

app/controllers/floors_controller.rb
class FloorsController < ApplicationController
  before_action :set_floor, only: [:show, :edit, :update, :destroy]

  # GET /floors
  # GET /floors.json
  def index
    if params[:building_id] == nil
      @floors = Floor.all
    else
      @floors = Floor.where("building_id = ?", params[:building_id])
    end
  end

  # GET /floors/1
  # GET /floors/1.json
  def show
  end

  # GET /floors/new
  def new
    @floor = Floor.new
  end

  # GET /floors/1/edit
  def edit
  end

  # POST /floors
  # POST /floors.json
  def create
    @floor = Floor.new(floor_params)

    respond_to do |format|
      if @floor.save
        format.html { redirect_to @floor, notice: 'Floor was successfully created.' }
        format.json { render :show, status: :created, location: @floor }
      else
        format.html { render :new }
        format.json { render json: @floor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /floors/1
  # PATCH/PUT /floors/1.json
  def update
    respond_to do |format|
      if @floor.update(floor_params)
        format.html { redirect_to @floor, notice: 'Floor was successfully updated.' }
        format.json { render :show, status: :ok, location: @floor }
      else
        format.html { render :edit }
        format.json { render json: @floor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /floors/1
  # DELETE /floors/1.json
  def destroy
    @floor.destroy
    respond_to do |format|
      format.html { redirect_to floors_url, notice: 'Floor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_floor
      @floor = Floor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def floor_params
      params.require(:floor).permit(:number, :code, :building_id)
    end
end

app/helpers/floors_helper.rb
module FloorsHelper
end

app/views/floors/_form.html.erb
<%= form_for(@floor) do |f| %>
  <% if @floor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@floor.errors.count, "error") %> prohibited this floor from being saved:</h2>

      <ul>
      <% @floor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :number %><br>
    <%= f.number_field :number %>
  </div>
  <div class="field">
    <%= f.label :code %><br>
    <%= f.text_field :code %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/floors/edit.html.erb
<h1>Editing floor</h1>

<%= render 'form' %>

<%= link_to 'Show', @floor %> |
<%= link_to 'Back', floors_path %>

app/views/floors/index.html.erb
<h1>Listing floors</h1>

<table>
  <tbody>
    <% @floors.each do |floor| %>
      <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
      	<td>
       		<%= floor.building.name %>
        </td>
        <td class="list_description">
        	<dl>
        		<dt><%= floor.number %></dt>
        		<dt>ID: <%= floor.id %></dt>
        		<dt><%= floor.code %></dt>
        	</dl>
        </td>
        <td class="list_actions">
        	<%= link_to 'Mobile Device App', navigator_index_path(:floor_id => floor.id) %><br/>
        	<%= link_to 'Layouts', layouts_path(:floor_id => floor.id) %><br/>
        	<%= link_to 'Show', floor %><br/>
        	<%= link_to 'Edit', edit_floor_path(floor) %><br/>
        	<%= link_to 'Destroy', floor, method: :delete, data: { confirm: 'Are you sure?' } %>
        	
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Floor', new_floor_path %>

app/views/floors/new.html.erb
<h1>New floor</h1>

<%= render 'form' %>

<%= link_to 'Back', floors_path %>

app/views/floors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Number:</strong>
  <%= @floor.number %>
</p>

<p>
  <strong>Code:</strong>
  <%= @floor.code %>
</p>

<p>
  <strong>Building:</strong>
  <%= @floor.building %>
</p>

<%= link_to 'Edit', edit_floor_path(@floor) %> |
<%= link_to 'Back', floors_path %>