config/routes.rb
Rails.application.routes.draw do
  
  match "/application.manifest" => Rails::Offline, via: [:get]

=begin
  offline = Rack::Offline.configure :cache_interval => 1 do
    cache ActionController::Base.helpers.asset_path("application.js")
    cache ActionController::Base.helpers.asset_path("jquery.tmpl.min.js")
    cache ActionController::Base.helpers.asset_path("jquery.offline.js")
    cache ActionController::Base.helpers.asset_path("json.js")
    cache ActionController::Base.helpers.asset_path("custom.js")
    cache ActionController::Base.helpers.asset_path("validate.js")
    cache ActionController::Base.helpers.asset_path("application.css")
    cache ActionController::Base.helpers.asset_path("style.css")
    cache ActionController::Base.helpers.asset_path("custom.css")
    
    public_path = Rails.public_path
    Dir[public_path.join("stylesheets/*.css")].each do |file|
      cache file.relative_path_from(public_path)
    end
    
    cache "/images/sb1.jpg"
    cache "/stylesheets/buildings.css"
    cache "/javascripts/buildings.js"
    
    network "/"
  end
  get "/application.manifest" => offline
=end
  
  get 'navigator/index'
  
  resources :layouts

  resources :floors

  resources :buildings

end

app/models/layout.rb
class Layout < ActiveRecord::Base
  belongs_to :floor
  
  validates :description, :file_location, :floor, presence: true
  #TODO: Validate that that the file location is correct
end

app/controllers/layouts_controller.rb
class LayoutsController < ApplicationController
  before_action :set_layout, only: [:show, :edit, :update, :destroy]

  # GET /layouts
  # GET /layouts.json
  def index
    if params[:floor_id] == nil
      @layouts = Layout.all
    else
      @layouts = Layout.where("floor_id = ?", params[:floor_id])
    end
  end

  # GET /layouts/1
  # GET /layouts/1.json
  def show
  end

  # GET /layouts/new
  def new
    @layout = Layout.new
  end

  # GET /layouts/1/edit
  def edit
  end

  # POST /layouts
  # POST /layouts.json
  def create
    @layout = Layout.new(layout_params)

    respond_to do |format|
      if @layout.save
        format.html { redirect_to @layout, notice: 'Layout was successfully created.' }
        format.json { render :show, status: :created, location: @layout }
      else
        format.html { render :new }
        format.json { render json: @layout.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /layouts/1
  # PATCH/PUT /layouts/1.json
  def update
    respond_to do |format|
      if @layout.update(layout_params)
        format.html { redirect_to @layout, notice: 'Layout was successfully updated.' }
        format.json { render :show, status: :ok, location: @layout }
      else
        format.html { render :edit }
        format.json { render json: @layout.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /layouts/1
  # DELETE /layouts/1.json
  def destroy
    @layout.destroy
    respond_to do |format|
      format.html { redirect_to layouts_url, notice: 'Layout was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_layout
      @layout = Layout.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def layout_params
      params.require(:layout).permit(:description, :file_location, :floor_id)
    end
end

app/helpers/layouts_helper.rb
module LayoutsHelper
end

app/views/layouts/_form.html.erb
<%= form_for(@layout) do |f| %>
  <% if @layout.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@layout.errors.count, "error") %> prohibited this layout from being saved:</h2>

      <ul>
      <% @layout.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :file_location %><br>
    <%= f.text_field :file_location %>
  </div>
  <div class="field">
    <%= f.label :floor_id %><br>
    <%= f.text_field :floor_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html manifest="/application.manifest">
<head>
  <title>Tunafish</title>
 <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class='<%= controller.controller_name %>'>

<%= yield %>

</body>
</html>

app/views/layouts/edit.html.erb
<h1>Editing layout</h1>

<%= render 'form' %>

<%= link_to 'Show', @layout %> |
<%= link_to 'Back', layouts_path %>

app/views/layouts/index.html.erb
<h1>Listing layouts</h1>

<table>
  <tbody>
    <% @layouts.each do |layout| %>
      <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
      	<td>
       		<%= layout.floor.building.name %>
       		<p>Floor: <%= layout.floor.number %></p>
        </td>
        <td class="list_description">
        	<dl>
        		<dt>Description: <%= layout.description %></dt>
        		<dt>ID: <%= layout.id %></dt>
        		<dt><%= layout.file_location %></dt>
        	</dl>
        </td>
        <td class="list_actions">
        	<%= link_to 'Show', layout %><br/>
        	<%= link_to 'Edit', edit_layout_path(layout) %><br/>
        	<%= link_to 'Destroy', layout, method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Layout', new_layout_path %>

app/views/layouts/new.html.erb
<h1>New layout</h1>

<%= render 'form' %>

<%= link_to 'Back', layouts_path %>

app/views/layouts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @layout.description %>
</p>

<p>
  <strong>File location:</strong>
  <%= @layout.file_location %>
</p>

<p>
  <strong>Floor:</strong>
  <%= @layout.floor %>
</p>

<%= link_to 'Edit', edit_layout_path(@layout) %> |
<%= link_to 'Back', layouts_path %>